main: antispam\AntiSpam
api: 1.13.0
load: STARTUP
name: AntiSpam
description: "antispam plugin"
version: 1.1
author: xBeastMode

permissions:
  spam.bypass:
    default: op
    description: "Allow bypassing the spam limit"
